<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>trialPHP</title>
</head>
<body>
    <?php
    echo '<p>this is a line generated by php script to html doc<p>';
    ?>
</body>
</html>